import type { Metadata } from "next";
import { Merriweather, PT_Sans } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '700', '900'],
})

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSans.variable} ${merriweather.variable} antialiased`}>{children}</body>
    </html>
  );
}
